CC = g++
CFLAG = -O3 -Wall -std=c++0x

compress_hirgc: compress_hirgc
	$(CC) compress_hirgc.cpp -o compress_hirgc $(CFLAG)

decompress_hirgc: decompress_hirgc.cpp
	$(CC) decompress_hirgc.cpp -o decompress_hirgc $(CFLAG)
